import type { PlatformConfig } from './type'
export const modelListConfig: PlatformConfig[] = [
  {
    // 模型对应的平台
    platform: 'OpenAI',
    // 模型分组
    group: 'openai',
    logo: 'https://qn.huat.xyz/mac/202404271224342.png',
    // 模型配置面板中按钮的状态
    enable: 1,
    apikey: '',
    apiKeyTitle: 'OpenAI API Key',
    apiKeyTip: '使用自己的 OpenAI Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: 'gpt-3.5-turbo',
        value: 'gpt-3.5-turbo',
        selected: 1,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-3.5-turbo-0125',
        value: 'gpt-3.5-turbo-0125',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-3.5-turbo-1106',
        value: 'gpt-3.5-turbo-1106',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-3.5-turbo-16k',
        value: 'gpt-3.5-turbo-16k',
        selected: 1,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-3.5-turbo-0613',
        value: 'gpt-3.5-turbo-0613',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-3.5-turbo-16k-0613',
        value: 'gpt-3.5-turbo-16k-0613',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4-turbo-preview',
        value: 'gpt-4-turbo-preview',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4-0125-preview',
        value: 'gpt-4-0125-preview',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4-vision-preview',
        value: 'gpt-4-vision-preview',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4',
        value: 'gpt-4',
        selected: 1,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4-0613',
        value: 'gpt-4-0613',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4-32k',
        value: 'gpt-4-32k',
        selected: 1,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4-32k-0613',
        value: 'gpt-4-32k-0613',
        selected: 0,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4-turbo',
        value: 'gpt-4-turbo',
        selected: 1,
        group: 'openai',
        desc: '',
      },
      {
        label: 'gpt-4o',
        value: 'gpt-4o',
        selected: 1,
        group: 'openai',
        desc: '',
      },
    ],
  },

  {
    platform: 'Moonshot AI',
    group: 'moonshot',
    logo: 'https://qn.huat.xyz/mac/202404281647092.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 Moonshot 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: 'Kimi',
        value: 'kimi',
        selected: 1,
        group: 'moonshot',
        desc: '',
      },
      {
        label: 'Kimi-no-search',
        value: 'kimi-silent_search',
        selected: 0,
        group: 'moonshot',
        desc: '不输出检索过程',
      },
      {
        label: 'moonshot-v1-8k',
        value: 'moonshot-v1-8k',
        selected: 0,
        group: 'moonshot',
        desc: '月之暗面',
      },
      {
        label: 'moonshot-v1-32k',
        value: 'moonshot-v1-32k',
        selected: 0,
        group: 'moonshot',
        desc: '月之暗面',
      },
      {
        label: 'moonshot-v1-128k',
        value: 'moonshot-v1-128k',
        selected: 0,
        group: 'moonshot',
        desc: '月之暗面',
      },
    ],
  },

  {
    platform: '智谱AI',
    group: 'glm',
    logo: 'https://qn.huat.xyz/mac/202404281700280.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 智谱AI 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: '智谱AI',
        value: 'glm',
        selected: 1,
        group: 'glm',
        desc: '',
      },
      {
        label: 'glm-no-search',
        value: 'glm-silent_search',
        selected: 0,
        group: 'glm',
        desc: '不输出检索过程',
      },
      {
        label: 'glm-4',
        value: 'glm-4',
        selected: 0,
        group: 'glm',
        desc: '智谱AI',
      },
      {
        label: 'gml-4v',
        value: 'gml-4v',
        selected: 0,
        group: 'glm',
        desc: '智谱AI',
      },
      {
        label: 'glm-3-turbo',
        value: 'glm-3-turbo',
        selected: 0,
        group: 'glm',
        desc: '智谱AI',
      },
    ],
  },

  {
    platform: '阶跃星辰',
    group: 'step',
    logo: 'https://qn.huat.xyz/mac/202404281706268.jpg',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 阶跃星辰 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: '阶跃星辰',
        value: 'step',
        selected: 1,
        group: 'step',
        desc: '',
      },
      {
        label: 'step-no-search',
        value: 'step-silent_search',
        selected: 0,
        group: 'step',
        desc: '不输出检索过程',
      },
      {
        label: 'step-1-32k',
        value: 'step-1-32k',
        selected: 0,
        group: 'step',
        desc: '阶跃星辰',
      },
      {
        label: 'step-1v-32k',
        value: 'step-1v-32k',
        selected: 0,
        group: 'step',
        desc: '阶跃星辰',
      },
      {
        label: 'step-1-200k',
        value: 'step-1-200k',
        selected: 0,
        group: 'step',
        desc: '阶跃星辰',
      },
    ],
  },

  {
    platform: '通义千问',
    group: 'qwen',
    logo: 'https://qn.huat.xyz/mac/202404281710457.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 通义千问 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: '通义千问',
        value: 'qwen',
        selected: 1,
        group: 'qwen',
        desc: '',
      },
      {
        label: 'qwen-no-search',
        value: 'qwen-silent_search',
        selected: 0,
        group: 'qwen',
        desc: '不输出检索过程',
      },

      {
        label: 'qwen-turbo',
        value: 'qwen-turbo',
        selected: 0,
        group: 'qwen',
        desc: '',
      },
      {
        label: 'qwen-plus',
        value: 'qwen-plus',
        selected: 0,
        group: 'qwen',
        desc: '',
      },

      {
        label: 'qwen-max',
        value: 'qwen-max',
        selected: 0,
        group: 'qwen',
        desc: '',
      },

      {
        label: 'qwen-max-0403',
        value: 'qwen-max-0403',
        selected: 0,
        group: 'qwen',
        desc: '',
      },
      {
        label: 'qwen-max-0107',
        value: 'qwen-max-0107',
        selected: 0,
        group: 'qwen',
        desc: '',
      },
      {
        label: 'qwen-max-1201',
        value: 'qwen-max-1201',
        selected: 0,
        group: 'qwen',
        desc: '',
      },
      {
        label: 'qwen-max-longcontext',
        value: 'qwen-max-longcontext',
        selected: 0,
        group: 'qwen',
        desc: '',
      },
    ],
  },

  {
    platform: '秘塔 AI',
    group: 'metaso',
    logo: 'https://qn.huat.xyz/mac/202404281720856.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        // 全网model名称支持 -> 简洁：concise / 深入：detail / 研究：research
        label: '秘塔AI-concise',
        value: 'concise',
        selected: 1,
        group: 'metaso',
        desc: '全网model名称支持 简洁: concise',
      },
      {
        // 全网model名称支持 -> 简洁：concise / 深入：detail / 研究：research
        label: '秘塔AI-detail',
        value: 'detail',
        selected: 1,
        group: 'metaso',
        desc: '全网model名称支持 深入: detail',
      },
      {
        // 全网model名称支持 -> 简洁：concise / 深入：detail / 研究：research
        label: '秘塔AI-research',
        value: 'research',
        selected: 1,
        group: 'metaso',
        desc: '全网model名称支持 研究: research',
      },

      {
        // 学术model名称支持 -> 学术-简洁：concise-scholar / 学术-深入：detail-scholar / 学术-研究：research-scholar
        label: '秘塔AI-concise-scholar',
        value: 'concise-scholar',
        selected: 1,
        group: 'metaso',
        desc: '学术model名称支持 学术-简洁: concise-scholar',
      },
      {
        // 学术model名称支持 -> 学术-简洁：concise-scholar / 学术-深入：detail-scholar / 学术-研究：research-scholar
        label: '秘塔AI-detail-scholar',
        value: 'detail-scholar',
        selected: 1,
        group: 'metaso',
        desc: '学术model名称支持 学术-深入: detail-scholar',
      },
      {
        // 学术model名称支持 -> 学术-简洁：concise-scholar / 学术-深入：detail-scholar / 学术-研究：research-scholar
        label: '秘塔AI-research-scholar',
        value: 'research-scholar',
        selected: 1,
        group: 'metaso',
        desc: '学术model名称支持 学术-研究: research-scholar',
      },
    ],
  },

  {
    platform: '讯飞星火',
    group: 'spark',
    logo: 'https://qn.huat.xyz/mac/202404281728356.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 讯飞星火 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: '讯飞星火',
        value: 'spark',
        selected: 1,
        group: 'spark',
        desc: '',
      },
      {
        label: 'spark-no-search',
        value: 'spark-silent_search',
        selected: 0,
        group: 'spark',
        desc: '讯飞星火: 不输出检索过程',
      },
    ],
  },

  {
    platform: '聆心智能',
    group: 'emohaa',
    logo: 'https://qn.huat.xyz/mac/202404281730582.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 讯飞星火 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: '聆心智能',
        value: 'emohaa',
        selected: 1,
        group: 'emohaa',
        desc: '',
      },
      {
        label: 'emohaa-no-search',
        value: 'emohaa-silent_search',
        selected: 0,
        group: 'emohaa',
        desc: '聆心智能: 不输出检索过程',
      },
    ],
  },

  {
    platform: '海螺 AI',
    group: 'minimaxi',
    logo: 'https://qn.huat.xyz/mac/202405072203103.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 minimaxi 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: '海螺 AI',
        value: 'hailuo',
        selected: 1,
        group: 'minimaxi',
        desc: '',
      },
    ],
  },

  {
    platform: 'Gemini',
    group: 'gemini',
    logo: 'https://qn.huat.xyz/mac/202404271453196.png',
    enable: 1,
    apikey: '',
    apiKeyTitle: 'API Key',
    apiKeyTip: '填入来自 Google 的 API Key',
    baseUrl: '',
    chatAPI: '/v1/chat/completions',
    baseUrlTitle: '接口代理地址',
    baseUrlTip: '除默认地址外，必须包含 http(s)://',
    modelListTitle: '模型列表',
    modelListTip: '选择在会话中展示的模型，选择的模型会在模型列表中展示',
    modelList: [
      {
        label: 'gemini-pro',
        value: 'gemini-pro',
        selected: 1,
        group: 'gemini',
        desc: '',
      },
      {
        label: 'gemini-1.0-pro-vision-latest',
        value: 'gpt-3.5-turbo-0125',
        selected: 0,
        group: 'gemini',
        desc: '',
      },
      {
        label: 'gemini-pro-vision',
        value: 'gemini-pro-vision',
        selected: 0,
        group: 'gemini',
        desc: '',
      },
      {
        label: 'gemini-1.0-pro-latest',
        value: 'gemini-1.0-pro-latest',
        selected: 0,
        group: 'gemini',
        desc: '',
      },
      {
        label: 'gemini-1.5-pro-latest',
        value: 'gemini-1.5-pro-latest',
        selected: 0,
        group: 'gemini',
        desc: '',
      },
      {
        label: 'gemini-ultra',
        value: 'gemini-ultra',
        selected: 0,
        group: 'gemini',
        desc: '',
      },
    ],
  },
]
